# Generated by Django 2.0 on 2018-11-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='student/%Y/%m/%d/', verbose_name='文件名称')),
            ],
            options={
                'verbose_name': '上传文件管理',
                'verbose_name_plural': '上传文件管理',
            },
        ),
        migrations.AlterField(
            model_name='studentname',
            name='studnet_id',
            field=models.CharField(max_length=150, verbose_name='学号'),
        ),
    ]
