# Generated by Django 2.0 on 2018-11-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181107_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='class_name',
            field=models.IntegerField(default=0, verbose_name='班级'),
        ),
    ]
