# Generated by Django 2.0 on 2018-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181107_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='studnet_id',
            field=models.CharField(max_length=100, verbose_name='学号'),
        ),
    ]
