# Generated by Django 2.0 on 2018-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10, verbose_name='班级')),
                ('studnet_id', models.CharField(max_length=100, verbose_name='学号')),
                ('student_name', models.CharField(max_length=15, verbose_name='名字')),
            ],
            options={
                'verbose_name': '学生花名册',
                'verbose_name_plural': '学生花名册',
            },
        ),
    ]
