# Generated by Django 2.0 on 2018-11-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20181107_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='class_name',
            field=models.CharField(default='', max_length=20, verbose_name='班级'),
        ),
    ]
