# Generated by Django 2.0 on 2018-11-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20181107_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='studnet_id',
            field=models.IntegerField(default='0', verbose_name='学号'),
        ),
    ]
