# Generated by Django 2.0 on 2018-11-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181107_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnet_id', models.CharField(max_length=100, verbose_name='学号')),
                ('student_name', models.CharField(max_length=15, verbose_name='名字')),
                ('class_name', models.CharField(max_length=20, verbose_name='考试班级')),
                ('seat_number', models.CharField(max_length=10, verbose_name='座位号')),
            ],
            options={
                'verbose_name': '考试座位表',
                'verbose_name_plural': '考试座位表',
            },
        ),
    ]
