# Generated by Django 2.0 on 2018-11-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_examseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examseat',
            name='seat_number',
            field=models.IntegerField(max_length=10, verbose_name='座位号'),
        ),
    ]
