# Generated by Django 2.0 on 2018-11-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20181107_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examseat',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='座位号'),
        ),
    ]
